feat: main footer
cesium/hydrogen pull request #44
Opened 2024-10-19 14:34 UTC by AfonsoMartins26

2024-11-23 17:55 UTC, AfonsoMartins26 commented on src/components/footer.tsx
`import React from 'react';` is such an heavy job, can you import only the necessary functions

2024-11-23 18:18 UTC, RicoPleasure commented on src/components/footer.tsx
ok, I'll change this next time I touch it. 
I will also make the code cleaner. It works but I will try to optimize the use of `{sections[0]?.items[0]` for instance.

2024-11-23 19:04 UTC, AfonsoMartins26 commented on package-lock.json
Also delete this because it was created for running the project with npm, but this project uses bun.
To use it, install bun:
```
asdf plugin add bun
asdf install bun latest
```
Then, inside the hydrogen project:
```
asdf install
``` 
And to run the project, just use:
```
bun run dev
```

2024-11-25 19:04 UTC, AfonsoMartins26 reviewed
Looks good to me 🚀 !

2024-11-25 19:22 UTC, joaodiaslobo submitted a review, later dismissed

2024-11-26 12:07 UTC, diogogmatos commented
Make sure to merge the main branch with this one (from the current branch, run: `git merge main`) to get the changes regarding internationalization, since they change a lot including the main page and layout paths (`app/page.tsx`/`app/layout.tsx` -> `app/[lang]/page.tsx`/`app/[lang]/layout.tsx`).

Also don't forget to include the Footer component in the layout of the app instead of "page.tsx" ;)

2024-11-27 10:57 UTC, diogogmatos commented
Please update the image paths to use these ones (they were introduced in the navbar PR). 🙏🏼 

![image](https://github.com/user-attachments/assets/d3023029-e6bd-4f58-92e1-8d271e97fa2f)

2024-11-27 11:08 UTC, diogogmatos commented
I think this padding (yellow bar) is not supposed to be here 🤔 

![image](https://github.com/user-attachments/assets/79851ea8-f223-4ef3-a7ff-362e3f96bfb3)

Removing that "mt-8" should fix it ;)

2024-11-27 18:26 UTC, RicoPleasure commented
It may have some way to do what I did with the svg's in different components. However, I think this way is very pleasant. Let me know how you prefer it. Thanks!

2024-11-27 19:05 UTC, diogogmatos requested changes

2024-11-27 19:05 UTC, diogogmatos commented on src/components/footer.tsx
> +                </a>
```suggestion
                <Link key={index} href={social.url} target="_blank" rel="noopener noreferrer">
                  <IconSocial type={social.icon} width={26} height={26} fill="#6C757D" />  
                </Link>
```

Let's always use Next/Link for links :)

2024-11-27 19:05 UTC, diogogmatos commented on src/components/footer.tsx
> +          <div className="flex w-full min-w-[300px] sm:min-w-[600px] space-x-[50px] sm:space-x-[20px]">
```suggestion
          <div className="flex w-full min-w-[300px] sm:min-w-[600px] space-x-[50px] sm:space-x-5">
```

2024-11-27 19:05 UTC, diogogmatos commented on src/components/footer.tsx
> +            <div className="flex flex-col sm:flex-row w-full sm:w-[300px] sm:space-x-[50px] space-y-[32px] sm:space-y-0">
```suggestion
            <div className="flex flex-col sm:flex-row w-full sm:w-[300px] sm:space-x-[50px] space-y-8 sm:space-y-0">
```

2024-11-27 19:05 UTC, diogogmatos commented on src/components/footer.tsx
> +              <div className="space-y-[12px]">
```suggestion
              <div className="space-y-3">
```

2024-11-27 19:05 UTC, diogogmatos commented on src/components/footer.tsx
> +              <div className="space-y-[12px] sm:hidden">
```suggestion
              <div className="space-y-3 sm:hidden">
```

2024-11-27 19:05 UTC, diogogmatos commented on src/components/footer.tsx
> +              <div className="hidden space-y-[12px] sm:block">
```suggestion
              <div className="hidden space-y-3 sm:block">
```

2024-11-27 19:05 UTC, diogogmatos commented on src/components/footer.tsx
> +            <div className="flex flex-col sm:flex-row w-full sm:w-[300px] space-y-[32px] sm:space-y-0">
```suggestion
            <div className="flex flex-col sm:flex-row w-full sm:w-[300px] space-y-8 sm:space-y-0">
```

2024-11-27 19:05 UTC, diogogmatos commented on src/components/footer.tsx
> +              <div className="space-y-[12px] sm:hidden">
```suggestion
              <div className="space-y-3 sm:hidden">
```

2024-11-27 19:05 UTC, diogogmatos commented on src/components/footer.tsx
> +              <div className="mr-[50px] hidden space-y-[12px] sm:block">
```suggestion
              <div className="mr-[50px] hidden space-y-3 sm:block">
```

2024-11-27 19:05 UTC, diogogmatos commented on src/components/footer.tsx
> +              <div className="space-y-[12px]">
```suggestion
              <div className="space-y-3">
```

2024-11-27 19:05 UTC, diogogmatos commented on src/components/footer.tsx
> +        <div className="my-[32px] h-0 border border-stroke sm:hidden"></div>
```suggestion
        <div className="my-8 h-0 border border-stroke sm:hidden"></div>
```

2024-11-28 14:36 UTC, diogogmatos approved these changes

2024-11-28 14:47 UTC, diogogmatos commented on src/internationalization/dictionaries/pt.json
> +  }
To simplify, maybe we could turn this into an array of sections and also include the link information of each item. This way, on the Footer code, we can just iterate through `dict.sections` with `map` and do what we need to do, wanna give it a try? 👀 

```suggestion
  "footer": {
    "sections": [{
        "title": "CeSIUM",
        "items": ["Notícias", "Sobre nós", "Equipa", "Departmentos"],
        "links": ["#", "#", "#", "#"]
      },
      {
        "title": "Atividades",
        "items": ["Projetos", "Eventos", "Parcerias"],
        "links": ["#", "#", "#", "#"]
      },
      {
        "title": "Estudantes",
        "items": ["Torna-te sócio", "Torna-te colaborador", "Anuário"],
        "links": ["#", "#", "#", "#"]
      },
      {
        "title": "Links Úteis",
        "items": ["Calendarium", "Blackboard", "Portal do Aluno", "Página de LEI"],
        "links": ["#", "#", "#", "#"]
      }]
  }
```

2025-01-01 18:21 UTC, nunom27 approved these changes
LGTM!!

2025-01-01 18:22 UTC, merged