Hero Section
cesium/hydrogen pull request #5
Opened 2023-07-27 18:04 UTC by GresosJ

2023-07-27 19:03 UTC, EnzoVieira requested changes

2023-07-29 00:28 UTC, GresosJ commented on app/page.tsx
> +      <HeroSection />
Done.

2023-07-29 00:28 UTC, GresosJ commented on components/HeroSection.tsx
> +                  : "col-span-1"
Done.

2023-07-29 19:48 UTC, EnzoVieira requested changes

2023-07-29 19:48 UTC, EnzoVieira commented on components/Banners.tsx
> +}
tailwind advises against constructing class names dynamically, instead, return the complete class names.

see [https://tailwindcss.com/docs/content-configuration#dynamic-class-names](url)

2023-07-30 22:28 UTC, MarioRodrigues10 requested changes

2023-07-30 22:28 UTC, MarioRodrigues10 commented on components/Banners.tsx
> +const items: string[][] = [
```suggestion
type LinkGroup = string[];
const items: LinkGroup[] = [
```

2023-07-30 22:28 UTC, MarioRodrigues10 commented on components/Banners.tsx
> +  links: string[];
```suggestion
  links: LinkGroup;
```

2023-07-31 16:43 UTC, merged